# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d84b913aeb807cb86aac1f438f896ba44fb73f1a760eb5a0fb4254cbd9979286b6e51101116af8e98848287161a2c78649e6c37ff5fa14634e6d272b8ccb74a

test:
  secret_key_base: 244d9d7a1c12eade6cfbc73ccbe57a71c23a79e25c291080de84e726d2ee8938da844bfd00caa054b3ce994217453da22f719b0ddfd822bff37e2399e870bbab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
